query getStores(
  $postalCode: String
  $pageNumber: Int
  $pageSize: Int
  $filterByTag: String
) {
  getStores(
    postalCode: $postalCode
    pageNumber: $pageNumber
    pageSize: $pageSize
    keyword: $filterByTag
  ) {
    items {
      distance
      name
      instructions
      id
      isActive
      address {
        postalCode
        country
        city
        state
        neighborhood
        street
        number
        complement
        reference
        location {
          latitude
          longitude
        }
      }
      pickupHolidays {
        date
        hourBegin
        hourEnd
      }
      businessHours {
        dayOfWeek
        openingTime
        closingTime
      }
    }
    paging {
      page
      pageSize
      total
      pages
    }
  }
}
