query getStore($id: String!) {
  pickupPoint(id: $id) @context(provider: "vtex.store-graphql") {
    businessHours {
      openingTime
      dayOfWeek
      closingTime
    }
    pickupHolidays {
      date
      hourBegin
      hourEnd
    }
    isActive
    distance
    friendlyName
    id
    instructions
    seller
    address {
      addressId
      cacheId
      id
      userId
      receiverName
      complement
      neighborhood
      country
      state
      number
      street
      geoCoordinates
      postalCode
      city
      reference
      addressName
      addressType
    }
  }
}
