query getStores($latitude: Float, $longitude: Float, $filterByTag: String)
  @context(provider: "vtex.store-locator") {
  getStores(latitude: $latitude, longitude: $longitude, keyword: $filterByTag) {
    items {
      distance
      name
      instructions
      id
      isActive
      address {
        postalCode
        country
        city
        state
        neighborhood
        street
        number
        complement
        reference
        location {
          latitude
          longitude
        }
      }
      pickupHolidays {
        date
        hourBegin
        hourEnd
      }
      businessHours {
        dayOfWeek
        openingTime
        closingTime
      }
    }
  }
}
